server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
    url: jdbc:mysql://localhost:3306/SpringCloudTry?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.api.entity

eureka:
  client:
    # means whether to register itself in Eureka Server, the default is true
    register-with-eureka: true

    # means whether to fetch data from Eureka Server, the default is true.
    # Single node mode doesn't matter but cluster must be set to true to work with ribbon.
    fetchRegistry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # Cluster mode
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001 # This is the instance id of this service
    prefer-ip-address: true  # To show the ip address of this service in Eureka Server (Usually in the lower left corner).
    lease-renewal-interval-in-seconds: 1 # The interval of renewal of lease(heart beat).
    lease-expiration-duration-in-seconds: 2 # The duration of lease(heart beat).