server:
  port: 80

spring:
  application:
    name: cloud-order-feign

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # Cluster mode
  instance:
    instance-id: order80
    prefer-ip-address: true

ribbon:
  # The time limit for connecting to the server. It depends on the network.
  ReadTimeout: 5000
  # The time limit for reading the available data from the server after the connection is established. It depends on the network.
  ConnectTimeout: 5000

logging:
  level:
    com.cloud.feign.service.PaymentFeignService: debug